name: SEPARATE
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.3
  - tifffile=2021.7.2
  - scipy=1.10.1
  - scikit-image=0.19.3
  - tqdm=4.65.0
  - tensorboard=2.6.0
  - matplotlib=3.7.1
  - networkx=2.8.4
  - yaml=0.2.5
  - pyyaml=6.0